config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :conversations do
    resources :messages
  end

  resources :matches

  resources :users

  post '/approve/:id' => 'matches#approve', as: :approve_user
  post '/decline/:id' => 'matches#decline', as: :decline_user
  get '/bravo' => 'matches#bravo', as: :bravo

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id =?)
		OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
	 	sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user

  def match
  end

  def approve
  end

  def decline
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%d/%m/%y à %l:%M %p")
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many_attached :photos

  validates :sex, presence: true
  validates :sex_preference, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def human_attribute_name
  end


  def matches
    liked_user_ids = Like.where(user_id: self.id).map(&:liked_user_id)
    likes_me_user_ids = Like.where(liked_user_id: self.id).map(&:user_id)

    matched_ids = liked_user_ids.select{ |id| likes_me_user_ids.include?(id) }

    User.where(id: matched_ids)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :photos, :sex, :sex_preference, :first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :photos, :sex_preference, :first_name, :last_name])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def new
    users = User.all
    @users = users.where.not(id: current_user.id)
  end

  def create
    existing_conversation = Conversation.between(params[:sender_id], params[:recipient_id])
    if existing_conversation.present?
      @conversation = existing_conversation.first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private

    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @users = User.where.not(id: current_user.id)
    @users = @users.where(sex: current_user.sex_preference, sex_preference: current_user.sex)
  end

  def matches
   @matches = current_user.matches

  end

  def approve
    user_id = params[:id]

    new_like = Like.new(liked_user_id: params[:id])
    new_like.user_id = current_user.id

    if new_like.save
      existing_like = Like.where(user_id: user_id, liked_user_id: current_user.id).count
      @they_like_us = existing_like > 0
    else 
      #TBD
    end
  end

  def decline
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do 
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)

    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private

    def message_params
      params.require(:message).permit(:body, :user_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def home
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @user.update!(user_params)

    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:photos, :first_name, :last_name, :nickname, :age, :sex_preference)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/conversations/index.html.erb
<hr>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h5>Hello
        <% if current_user.email === 'martin@gmail.com' %>
          Master of the Tinder universe, choisi avec qui tu veux discuter :
        <% else %>
          <%= current_user.first_name %>, choisi avec qui tu veux discuter :
        <% end %>
      </h5>
    </div>
  </div>

<% if current_user.matches.length > 0 %>
  <% current_user.matches.each do |match| %>
  <% Conversation.create(sender_id: current_user.id, recipient_id: match.id)%>
  
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <div class="background-conversation">
          <% @conversations.each do |conversation| %>
            <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
              <% if conversation.sender_id == current_user.id %>
                <% recipient = User.find(conversation.recipient_id) %>
              <% else %>
                <% recipient = User.find(conversation.sender_id) %>
              <% end %>
              <h5><%= link_to recipient.email, conversation_messages_path(conversation)%></h5>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end%>

  <div class="row">
    <div class="col-sm-12 col-lg-6">
      <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<div>
  <h1>A qui veux-tu écrire ?</h1>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.email,
          conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post"%>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
</div>

app/views/layouts/_navbar.html.erb
<%# <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <p class="h5 my-0 me-md-auto fw-normal">Company name</p>
  <nav class="my-2 my-md-0 me-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <a class="btn btn-outline-primary" href="#">Sign up</a>
</header> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Martinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <!-- handle asset pipeline -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- handle bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

     <!-- handle webpack -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>
  
  <body>
    <div class="container">
      <div class='item row justify-content-around'>
        <%#= render 'layouts/navbar' %>
        <div class='item'>
          <%= render 'devise/menu/registration_items' %>
        </div>
        <div class='item'>
          <%= render 'devise/menu/login_items' %>
        </div>
      </div>
    <%= yield %>
    </div>

  </body>
</html>

app/views/matches/index.html.erb
<div>
  <ul id="slides">
    <% @users.each_with_index do |user, i| %>
      <li class="slide <%= 'showing' if i == 0 %>" data-id="<%=user.id%>" >
        <% if user.photos.length > 0 %>
          <% user.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 450, width: 350, crop: :fill %>
          <% end %>
        <% end %>
        <span class="user-details"> <%= user.nickname %>,<%= user.age %></span> 
      </li>
    <% end%>

  </ul>
  <div id='slide-controls'>
    <span id="decline"><i class="fa fa-times-circle fa-3x"></i></span>
    <span id="approve"><i class="fa fa-heart fa-3x"></i></span>
  </div>
</div>



  <div class='button-controls'>
    <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
  </div>

app/views/matches/matches.html.erb
Bravo tu as matché ! 
Tu peux maintenant écrire à ton Roméo !

<div>
  <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
</div>

app/views/messages/index.html.erb
<style>
  .icon-flipped {
  transform: scaleX(-1);
  -moz-transform: scaleX(-1);
  -webkit-transform: scaleX(-1);
  -ms-transform: scaleX(-1);
  }
  .glyphicon.glyphicon-log-out {
    font-size: 20px;
}
</style>
<div class="panel panel-default">
<% if @over_5 %>
 <%= link_to 'Show All', '?m=all', class: 'btn btn-link pull-right' %>
<% end %>
<%= link_to '<i class="glyphicon glyphicon-log-out icon-flipped"></i>'.html_safe,
'/conversations', { :class => 'tooltips, btn btn-link', 'data-toggle' => 'tooltip',
   'data-placement' => 'right', :title => 'Back To Inbox' } %>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
 <% @messages.each do |message| %>
  <% if message.body %>
   <% user = User.find(message.user_id) %>
   <div class="item">
<div class="panel-heading">
       <div class="header"><strong><%= user.email %> </strong><%= message.message_time %></div>
      <div class="list">
       <div class="item">
        <i class="right triangle icon"></i>
        <%= message.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>
</div>
<div class="col-md-10 col-md-offset-1">
<%= form_for [@conversation, @message] do |f| %>
<div class="form-group">
  <%= f.text_area :body, class: "form-control" %>
</div>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
<div class="form-group">
  <%= f.submit "Send Reply", class: "form-control btn btn-primary" %>
</div>
<% end %>
</div>

<div>
  <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
</div>

app/views/pages/home.html.erb
 <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <div class="flexbox home-container container">
      <div class="item row">
        <div class="col-12 col-lg-4">
          <p>
            <span id="banner-typed-text"></span>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-12 col-lg-4">
          <% if @user.photos.length > 0 %>
            <% @user.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 50, width: 50, crop: :fill, :radius=>"max" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="home-container">
      <div class="item row">
        <div class="col-12 col-lg-4">
          <p>  Que veux-tu faire aujourd'hui ?</p>
          <div class="item">
            <%= link_to "Matcher !", matches_path, :class => "btn btn-primary" %>
          </div>
          <div  class="item">
            <%= link_to "Voir mes discussions !", conversations_path, :class => "btn btn-primary" %>
          </div>
          <div  class="item">
            <%= link_to "Pimper mes Photos !", edit_user_path(@user.id, :profil => false), :class => "btn btn-primary" %>
          </div>
          <div  class="item">
            <%= link_to "Pimper mon Profil !", edit_user_path(@user.id, :profil => true), :class => "btn btn-primary" %>
          </div>
            <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" class="item">
    Je veux un compliment
  </button>
        </div>
      </div>
    </div>
  </div>



  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% compliments = 
          [
            "Tu es un vrai canon de beauté", 
            "Tu es ma star", 
            "Tu as un corps de rêve", 
            "Coucou beauté fatale"
          ]%>
        <%= compliments[rand(0..3)] %>      
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Merci !</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="global-container">
  <div class="container" %>
      <div class="row" %>
        <div class="col-12 col-lg-4">
          <%= simple_form_for @user do |f| %>
            <% if params[:profil] === 'true' %>
              <%= f.input :first_name %>
              <%= f.input :last_name %>
              <%= f.input :nickname %>
              <%= f.input :age, collection: 18..77 %>
              <%= f.input :sex_preference, as: :radio_buttons, collection: [['female', 'female'], ['male', 'male']] %>
            <% else %>
              <% if @user.photos.length > 0 %>
                  <% @user.photos.each do |photo| %>
                    <%= cl_image_tag photo.key, height: 350, width: 300, crop: :fill %>
                  <% end %>
                  <%= f.file_field :photos %>
              <% else %>
                <%= f.file_field :photos %>
              <% end %>
            <% end %>
            <%= f.button :submit, class: "btn btn-info" %>
          <% end %>

      </div>
    </div>
  </div>
  <div class="row">
    <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="global-container container">
  <div class="row">
    <% @user.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 350, width: 300, crop: :fill %>
    <% end %>
    <ul>
      <li> Ton âge: <%= @user.age %></li>
      <li> Ton prénom: <%= @user.first_name %> </li>
      <li> Ton nom: <%= @user.last_name %> </li>
      <li> Ton surnom: <%= @user.nickname %> </li>
    <ul>
  </div>

  <div class="row">
    <%= link_to "Retour", root_path, :class => "btn btn-primary" %>
  </div>
</div>